ungrouped:
  hosts:
    managedhost-app1:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2223
      ansible_user: root
    managedhost-app2:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2224
      ansible_user: root
    managedhost-app3:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2225
      ansible_user: root

app_group:
  hosts:
    managedhost-app1:
    managedhost-app2:
    managedhost-app3:
